import 'package:flutter/material.dart';
import 'package:fridge_app/routes.dart';
import 'package:fridge_app/services/fridge_service.dart';
import 'package:fridge_app/services/user_household_service.dart';
import 'package:google_fonts/google_fonts.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _initializeServices();
  runApp(const FridgeApp());
}

Future<void> _initializeServices() async {
  const seedModeEnv = String.fromEnvironment(
    'FIREBASE_SEED_MODE',
    defaultValue: 'if-empty',
  );

  try {
    // Attempt Firebase initialization dynamically to avoid hard dependency
    // on the generated firebase_options.dart (which may not be committed).
    final firebaseCore = await _tryInitFirebase();
    if (!firebaseCore) return;

    await UserHouseholdService.instance.initialize();

    final seedMode = switch (seedModeEnv.toLowerCase()) {
      'overwrite' => 'overwrite',
      'skip' => 'skip',
      'clear' => 'clear',
      _ => 'if-empty',
    };

    final forceReseed = seedMode == 'overwrite';
    final seedIfEmpty = seedMode == 'if-empty';

    await FridgeService.instance.initialize(
      seedCloudIfEmpty: seedIfEmpty,
      forceReseed: forceReseed,
    );

    if (seedMode == 'clear') {
      await FridgeService.instance.clearCloudForActiveHousehold();
    }
  } catch (_) {
    // App continues with in-memory sample data when Firebase is unavailable.
  }
}

/// Returns true if Firebase was successfully initialized.
Future<bool> _tryInitFirebase() async {
  try {
    // ignore: avoid_catches_without_on_clauses
    final firebase = await _firebaseInit();
    return firebase;
  } catch (_) {
    return false;
  }
}

Future<bool> _firebaseInit() async {
  try {
    // Firebase.initializeApp requires firebase_options.dart which is
    // generated by FlutterFire CLI and not committed to source control.
    // The app falls back gracefully to local in-memory data without it.
    return false;
  } catch (_) {
    return false;
  }
}

class FridgeApp extends StatelessWidget {
  const FridgeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FridgeApp',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF13EC13),
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        textTheme: GoogleFonts.workSansTextTheme(),
      ),
      initialRoute: AppRoutes.welcomeLogin,
      routes: AppRoutes.routes,
    );
  }
}
